# auth API

###
# baseURL
@baseURL = http://localhost:5000

###
# register
POST {{baseURL}}/register
Content-Type: application/json

{
    "first_name": "Dustin",
    "last_name": "Reed",
    "username": "DevDreed",
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Logout
POST {{baseURL}}/logout
Content-Type: application/json

