# users API

###
# baseURL
@baseURL = http://localhost:5000

###
# Find All Users
GET {{baseURL}}/users

###
# Find User By WRONG Id
GET {{baseURL}}/users/1

###
# Find User By Id
GET {{baseURL}}/users/714eb5c5-bcab-4d8f-b021-4a5b4b1015af

###
# Add User
POST {{baseURL}}/users
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Update User
PUT {{baseURL}}/users/72d5cb6c-1301-4ee6-805b-021c91aa9ed0
Content-Type: application/json

{
    "first_name": "Dustin",
    "last_name": "Reeddddddddd",
    "username": "DevDreed",
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Del User By Id
DELETE {{baseURL}}/users/1
